name: "Build Android app"

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout Respository
          uses: actions/checkout@v4

        - name: Setting Node
          uses: actions/setup-node@v4

        - name: Java Setup
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'zulu'

        - name: Validate gradle wrapper
          uses: gradle/wrapper-validation-action@v3

        - name: Run Yarn Install
          run: yarn install

        - name: Build Application
          run: cd android && ./gradlew assembleRelease

        - name: Upload Build
          uses: actions/upload-artifact@v4
          with:
            name: app
            path: ./android/app/build/outputs/apk/release/app-release.apk
            retention-day: 3
